StudentCalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as v


urlpatterns = [
    path(r'', v.login_view),
    path(r'admin/', admin.site.urls),
    path(r'accounts/', include('accounts.urls')),
    path(r'calendar/', include('cal.urls')),
]

cal/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from . import views


app_name = 'cal'
urlpatterns = [
    path(r'', login_required(views.CalendarView.as_view()), name='calendar'),
    path(r'activitate/<int:pk>/', views.ActivitateDetailView.as_view(), name='activitate_detail'),
    path(r'list_discipline/', views.DisciplinaListView.as_view(), name='disciplina_list'),
    path(r'ascunde/<int:pk>/', views.hide, name="hide"),
    path(r'schimba-seminar/<int:pk>/', views.list_group, name="list_group"),
    path(r'schimba-grupa/<int:old_pk>/<int:new_pk>/', views.change_group, name="change_group"),
]

cal/models.py
from django.db import models
from .constants import TipActivitateDisciplina



class Repart(models.Model):
    frecventa = models.IntegerField(default=0, choices=((0, 'saptamanal'), (1, 'saptamana 1'), (2, 'saptamana 2')))
    semestru = models.ForeignKey('Semestru', on_delete=models.CASCADE)
    disciplina = models.ForeignKey('Disciplina', on_delete=models.CASCADE)
    formatie = models.ForeignKey('Formatie', on_delete=models.CASCADE)
    cadru = models.ForeignKey('Cadru', on_delete=models.CASCADE)
    sala = models.ForeignKey('Sala', on_delete=models.CASCADE)
    zi = models.ForeignKey('Zi', on_delete=models.CASCADE)
    tip_activitate = models.CharField(max_length=1, choices=TipActivitateDisciplina.CHOICES)
    nr_ore = models.IntegerField(blank=True)
    ora_i = models.IntegerField(null=False)
    ora_s = models.IntegerField(null=False)


class Semestru(models.Model):
    numar = models.IntegerField(choices=((1, 'I'), (2, 'II')))
    tip_an = models.CharField(default='NT', blank=True, max_length=10, choices=(('NT', 'Neterminal'), ('T', 'Terminal')))
    numar_saptamani = models.IntegerField(default=14, choices=((14, '14 săptămâni'), (12, '12 săptămâni')))
    data_inceput = models.DateField()
    data_sfarsit = models.DateField()

    def __str__(self):
        return str(self.numar)+', '+str(self.tip_an)


class StructuraSemestru(models.Model):
    semestru = models.ForeignKey('Semestru', on_delete=models.CASCADE, related_name="structuri_semestru")
    limbi_predare = models.ManyToManyField('accounts.LimbaPredare')
    descriere = models.CharField(max_length=100, blank=False)

    def get_limbi_predare(self):
        return "\n".join([lb.denr for lb in self.limbi_predare.all()])

    def __str__(self):
        return self.descriere


class ActivitateNedidactica(models.Model):
    structura = models.ForeignKey('StructuraSemestru', null=True, on_delete=models.CASCADE, related_name="activitati_nedidactice")
    data_inceput = models.DateField()
    data_sfarsit = models.DateField()
    descriere = models.CharField(max_length=50, blank=False)

    def __str__(self):
        return self.descriere


class Cadru(models.Model):
    nume = models.CharField(max_length=30, null=False)
    web = models.CharField(max_length=50, blank=True, default='')
    catedra = models.ForeignKey('Catedra', on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    activ = models.IntegerField(default=1)  # by default is active
    cod = models.CharField(max_length=5)

    def __str__(self):
        return self.nume


class Sala(models.Model):
    cod = models.CharField(max_length=10, null=False)
    legenda = models.CharField(max_length=80, default='')
    cladire = models.ForeignKey('Cladire',on_delete=models.CASCADE)

    def __str__(self):
        return self.cod


class Cladire(models.Model):
    denr = models.CharField(max_length=40, null=False)
    descriere = models.CharField(max_length=100,blank=True)

    def __str__(self):
        return self.denr


class Zi(models.Model):
    cod = models.IntegerField(null=False)
    denr = models.CharField(max_length=8, null=False)

    def __str__(self):
        return str(self.cod)


class Formatie(models.Model):
    an = models.IntegerField()
    cod = models.CharField(max_length=10, null=False)
    denumire = models.CharField(max_length=20, blank=True)
    nivel = models.IntegerField()
    componenta = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.cod


class Disciplina(models.Model):
    cod = models.CharField(max_length=10, null=False, default='')
    denr = models.CharField(max_length=120, null=False)

    def __str__(self):
        return self.denr


class Catedra(models.Model):
    denr = models.CharField(max_length=50, null=False)

    def __str__(self):
        return self.denr


class Post(models.Model):
    nume = models.CharField(max_length=20, null=False, default='')
    denr = models.CharField(max_length=50, null=False)

    def __str__(self):
        return self.denr

cal/views.py
import calendar
from datetime import timedelta
import datetime

from django.shortcuts import redirect, render
from django.views import generic
from django.utils.safestring import mark_safe
from django.views.generic import DetailView, ListView
from accounts.models import Profil, Activitate
from .models import *
from .utils import Calendar


class CalendarView(generic.ListView):
    model = Repart
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.request.user.id
        profil = Profil.objects.filter(user_id=user_id).first()
        context['id_profil'] = profil.id

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month, profil)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)

        return context


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return datetime.date(year, month, day=1)
    return datetime.date.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def change_group(request, old_pk, new_pk):
    new_disc = Repart.objects.get(pk=new_pk)
    Activitate.objects.create(profil=request.user.profil, disciplina=new_disc)
    old_disc = Repart.objects.get(pk=old_pk)
    Activitate.objects.filter(profil=request.user.profil, disciplina=old_disc).delete()

    return redirect('cal:disciplina_list')


def list_group(request, pk):
    disc = Repart.objects.get(pk=pk)
    denumire = disc.disciplina.denr
    componenta = disc.formatie.componenta
    discipline = Repart.objects.filter(disciplina__denr=denumire, tip_activitate=disc.tip_activitate).exclude(formatie__componenta=componenta)
    error = 'Nu exista alte grupe!'
    return render(request, 'cal/change_group.html', context={'discipline': discipline, 'current_disc': disc, 'error':error })


def hide(request, pk):
    activitate = Activitate.objects.filter(id=pk).first()
    if activitate:
        if not activitate.hidden:
            activitate.hidden = True
        else:
            activitate.hidden = False
        activitate.save()
        return redirect('cal:disciplina_list')
    error = 'Activitatea pe care vreti sa o ascundeti nu exista!'
    return redirect('cal:disciplina_list', context={'error': error, })


class DisciplinaListView(ListView):
    template_name = 'cal/disciplina_list.html'
    context_object_name = 'activitati'

    def get_queryset(self):
        return Activitate.objects.filter(profil_id=self.request.user.profil)


class ActivitateDetailView(DetailView):
    template_name = 'cal/activitate_detail.html'

    def get_queryset(self):
        return Activitate.objects.filter(profil_id=self.request.user.profil)

cal/templates/cal/activitate_detail.html
{% extends 'homepage.html' %}

{% block content %}
<h4> {{object.disciplina.disciplina}}</h4>
{% if object.disciplina.tip_activitate == 'C' %}
<p>CURS</p>
{% elif object.disciplina.tip_activitate == 'S' %}
<p>SEMINAR</p>
{% else %}
<p>LABORATOR</p>
{% endif %}
<p>Zi: {{object.disciplina.zi.denr}}</p>
<p>Ora: {{object.disciplina.ora_i}}-{{object.disciplina.ora_s}}</p>
<p>Sala: {{object.disciplina.sala}}</p>
<p>Cadru: {{object.disciplina.cadru}}</p>
{% endblock %}

cal/templates/cal/base.html
<!--{% load static %}-->

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

cal/templates/cal/calendar.html
{% extends 'homepage.html' %}

{% block sidebar %}

{% endblock %}


{% block content %}

<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
</div>
{{ calendar}}

{% endblock %}

cal/templates/cal/change_group.html
{% extends 'homepage.html' %}

{% block content %}

{% if current_disc %}
<h3>{{current_disc.disciplina.denr}}</h3>
{% endif %}

{% if discipline %}
    {% for disciplina in discipline %}
    <p>{{disciplina.formatie.componenta}}, {{disciplina.ora_i}}-{{disciplina.ora_s}}<a href="{% url 'cal:change_group' current_disc.id disciplina.id %}">Schimba</a></p>
    {% endfor %}
{% endif %}

{% if error %}
<p>{{error}}</p>
{% endif %}
{% endblock %}

cal/templates/cal/disciplina_list.html
{% extends 'homepage.html' %}

{% block content %}

{% if activitati %}
    {% if error %}
        <p>{{error}}</p>
    {% endif %}
    {% for activitate in activitati %}
    <p>{{activitate.disciplina.disciplina.denr}}, {{activitate.disciplina.tip_activitate}}</p>
    <p>
            {% if activitate.hidden == True %}
            <a class="btn btn-warning" href="{% url 'cal:hide' activitate.id %}">Afiseaza</a>
            {% else %}
            <a class="btn btn-danger" href="{% url 'cal:hide' activitate.id %}">Ascunde</a>
            {% endif %}
            {% if activitate.disciplina.tip_activitate == 'S' or activitate.disciplina.tip_activitate == 'L' %}
            <a class="btn btn-info" href="{% url 'cal:list_group' activitate.disciplina.id%}">Adauga de la alta grupa</a>
            {% endif %}
        </p>
    {% endfor %}
{% endif %}


{% endblock %}