StudentCalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as v


urlpatterns = [
    path(r'', v.login_view),
    path(r'admin/', admin.site.urls),
    path(r'accounts/', include('accounts.urls')),
    path(r'calendar/', include('cal.urls')),
]

accounts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from .views import (
    register, ProfileUpdateView,
    load_limba_predare, login_view,
    logout_request,
    load_an, load_grupa,
    delete_profil)

app_name = 'accounts'
urlpatterns = [
    path(r'register/', register, name='register'),
    path(r'login/', login_view, name="login_view"),
    path(r'logout/', logout_request, name='logout'),
    path(r'profil/', login_required(ProfileUpdateView.as_view()), name='profil_change'),
    path(r'delete_profil/', delete_profil, name='delete_profil'),
    # path(r'profil<int:pk>/', ProfileDetailView.as_view(), name='profil_detail'),



    path('ajax/load-lb/', load_limba_predare, name='ajax_load_lb'),
    path('ajax/load-an/', load_an, name='ajax_load_an'),
    path('ajax/load-grupa/', load_grupa, name='ajax_load_grupa'),
]


cal/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from . import views


app_name = 'cal'
urlpatterns = [
    path(r'', login_required(views.CalendarView.as_view()), name='calendar'),
    path(r'activitate/<int:pk>/', views.ActivitateDetailView.as_view(), name='activitate_detail'),
    path(r'list_discipline/', views.DisciplinaListView.as_view(), name='disciplina_list'),
    path(r'ascunde/<int:pk>/', views.hide, name="hide"),
    path(r'schimba-seminar/<int:pk>/', views.list_group, name="list_group"),
    path(r'schimba-grupa/<int:old_pk>/<int:new_pk>/', views.change_group, name="change_group"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.db.models.signals import post_save
from django.dispatch import receiver

from cal.models import Repart


class MyUserManager(BaseUserManager):

    def create_user(self, email, nume, prenume, password=None):

        if not email:
            raise ValueError('Utilizatorii trebuie sa aiba o adresa de email')

        user = self.model(
            email=self.normalize_email(email),
            nume=nume,
            prenume=prenume,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nume, prenume, password):
        user = self.create_user(
            email,
            password=password,
            nume=nume,
            prenume=prenume,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(verbose_name='adresa de email',
                              max_length=255,
                              unique=True,)
    nume = models.CharField(max_length=25, blank=False)
    prenume = models.CharField(max_length=25, blank=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nume', 'prenume']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        # Does the user have a specific permission?
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        # Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        # Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


@receiver(post_save, sender=MyUser)
def create_profile(sender, instance, created, **kwargs):
    if created:
        profil = Profil.objects.create(user=instance)
        profil.save()


post_save.connect(create_profile, sender=MyUser)


class Specializare(models.Model):
    denr = models.CharField(max_length=50)

    def __str__(self):
        return self.denr


class LimbaPredare(models.Model):
    structura = models.ForeignKey
    specializare = models.ForeignKey(Specializare, on_delete=models.CASCADE, related_name='limbi_predare')
    denr = models.CharField(max_length=8)
    
    def __str__(self):
        return self.denr + ',' + self.specializare.__str__()
    

class An(models.Model):
    limba_predare = models.ForeignKey(LimbaPredare, on_delete=models.CASCADE, related_name='ani')
    denr = models.IntegerField(choices=((1,'I'),(2,'II'),(3,'III')))
    
    def __str__(self):
        return str(self.denr)+','+self.limba_predare.__str__()


class Grupa(models.Model):
    an = models.ForeignKey(An, on_delete=models.CASCADE, related_name='grupe')
    denr = models.CharField(max_length=5)
    
    def __str__(self):
        return self.denr


class Profil(models.Model):
    user = models.OneToOneField('MyUser', on_delete=models.CASCADE, related_name='profil')
    universitate = models.CharField(max_length=26, default='Universitatea Babeș-Bolyai', editable=False)
    facultate = models.CharField(max_length=39, default='Facultatea de Matematică și Informatică', editable=False)
    specializare = models.ForeignKey(Specializare, on_delete=models.SET_NULL, null=True)
    limba_predare = models.ForeignKey(LimbaPredare, on_delete=models.SET_NULL, null=True)
    an = models.ForeignKey(An, on_delete=models.SET_NULL, null=True)
    grupa = models.ForeignKey(Grupa, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.user.__str__()+', '+self.grupa.__str__()


class Activitate(models.Model):
    profil = models.ForeignKey('Profil', on_delete=models.CASCADE, related_name="activitati")
    disciplina = models.ForeignKey('cal.Repart', on_delete=models.CASCADE)
    hidden = models.BooleanField(default=False)


@receiver(post_save, sender=Profil)
def create_orar(sender, instance, created, **kwargs):
    if not created:
        if instance.grupa is not None:
            activitati = Repart.objects.filter(formatie__componenta__contains=instance.grupa)
            Activitate.objects.filter(profil=instance).delete()
            if activitati.exists():
                for activitate in activitati.iterator():
                    Activitate.objects.create(profil=instance, disciplina=activitate)
                

post_save.connect(create_orar, sender=Profil)


accounts/forms.py
from django import forms
from .models import MyUser, Profil, LimbaPredare, Grupa, An
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = MyUser
        fields = ['email', 'nume', 'prenume', 'password1', 'password2']


class ProfilForm(forms.ModelForm):
    class Meta:
        model = Profil
        fields = ('specializare', 'limba_predare', 'an', 'grupa')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['limba_predare'].queryset = LimbaPredare.objects.none()
        self.fields['an'].queryset = An.objects.none()
        self.fields['grupa'].queryset = Grupa.objects.none()
        print(self.instance.pk)
        # SPECIALIZARE
        if 'specializare' in self.data:
            print(self.data)
            try:
                specializare_id = int(self.data.get('specializare'))
                self.fields['limba_predare'].queryset = LimbaPredare.objects.filter(specializare_id=specializare_id).order_by('denr')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            if self.instance.specializare is not None:
                self.fields['limba_predare'].queryset = self.instance.specializare.limbi_predare.all().order_by('denr')

        # LIMBA PREDARE
        if 'limba_predare' in self.data:
            try:
                limba_predare_id = int(self.data.get('limba_predare'))
                self.fields['an'].queryset = An.objects.filter(limba_predare_id=limba_predare_id).order_by('denr')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            if self.instance.limba_predare is not None:
                self.fields['an'].queryset = self.instance.limba_predare.ani.all().order_by('denr')

        # AN
        if 'an' in self.data:
            try:
                an_id = int(self.data.get('an'))
                self.fields['grupa'].queryset = Grupa.objects.filter(an_id=an_id).order_by('denr')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            if self.instance.an is not None:
                self.fields['grupa'].queryset = self.instance.an.grupe.all().order_by('denr')

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, ProfilForm

from django.views.generic import UpdateView, DetailView
from django.urls import reverse_lazy, reverse
from .models import Profil, LimbaPredare, An, Grupa, MyUser


def index(request):
    return render(request, 'homepage.html')


def delete_profil(request):
    deletion = str(request.user.prenume)+", contul tau a fost sters!"
    MyUser.objects.get(id=request.user.id).delete()
    logout(request)
    return render(request, 'accounts/login.html', context={'deletion_massage': deletion})


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data['password1']
            messages.success(request, f'Account created for {email}!')
            new_user = authenticate(request, email=email, password=password)
            login(request,  new_user)
            return redirect(reverse_lazy('accounts:profil_change'))
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        email = request.POST.get('email', '')
        password = request.POST.get('password', '')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('cal:calendar')
        else:
            error = 'Datele introduse nu sunt valide!'
            return render(request, 'accounts/login.html', context={'error': error, })
    return render(request, 'accounts/login.html')


def logout_request(request):
    logout(request)
    messages.info(request, 'Ai iesit din cont!')
    return redirect('accounts:login_view')

'''
class ProfileDetailView(DetailView):
    template_name = 'accounts/profil_detail.html'
    queryset = Profil.objects.all()
'''


class ProfileUpdateView(UpdateView):
    model = Profil
    form_class = ProfilForm
    # fields = ('specializare', 'limba_predare', 'an', 'grupa')

    def get_object(self, queryset=None):
        return self.request.user.profil

    def get_success_url(self, **kwargs):
        print(self.object.user)
        # return reverse_lazy('cal:calendar', args=(self.object.user.id,))
        return reverse_lazy('cal:calendar')


def load_limba_predare(request):
    specializare_id = request.GET.get('specializare')
    limbi_predare = LimbaPredare.objects.filter(specializare_id = specializare_id).order_by('denr')
    context = {'limbi_predare': limbi_predare}
    return render(request, 'accounts/limba_predare_options.html', context)


def load_an(request):
    limba_predare_id = request.GET.get('limba_predare')
    ani = An.objects.filter(limba_predare_id=limba_predare_id).order_by('denr')
    context = {'ani': ani}
    return render(request, 'accounts/an_options.html', context)


def load_grupa(request):
    an_id = request.GET.get('an')
    grupe = Grupa.objects.filter(an_id=an_id).order_by('denr')
    context = {'grupe': grupe}
    return render(request, 'accounts/grupa_options.html', context)

accounts/templates/accounts/an_options.html
<option value="">---------</option>
{% for an in ani %}
<option value="{{ an.pk }}">{{ an.denr }}</option>
{% endfor %}

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {% block content %}
  {% endblock %}
</body>
</html>

accounts/templates/accounts/grupa_options.html


<option value="">---------</option>
{% for grupa in grupe %}
<option value="{{ grupa.pk }}">{{ grupa.denr }}</option>
{% endfor %}

accounts/templates/accounts/limba_predare_options.html

<option value="">---------</option>
{% if limbi_predare
{% for limba_predare in limbi_predare %}
<option value="{{ limba_predare.pk }}">{{ limba_predare.denr }}</option>
{% endfor %}

accounts/templates/accounts/login.html
{% extends 'homepage.html' %}
{% block brand %}

<h6>Agenda Student</h6>
{% endblock %}
{% block content %}

<h2>Login</h2>

<form method="POST">
    {% csrf_token %}
    <label for="email">Email:</label>
    <input type="text" name="email" value="" id="email">
    <label for="password">Parola</label>
    <input type="password" name="password" value="" id="password">
    <button type="submit">Login</button>
    {% if error %}
    <div class="alert alert-warning" role="alert">{{error}}</div>
    {% elif deletion_massage %}
    <div class="alert alert-warning" role="alert">{{deletion_massage}}</div>
    {% endif %}
    <div class="border-top pt-3">
        <small class="text-muted">
            Nu ai cont?<a class="ml-2" href="{% url 'accounts:register' %}">Creeaza un cont</a></small>
    </div>
</form>

{% endblock %}

accounts/templates/accounts/profil_detail.html
{% extends 'homepage.html' %}

accounts/templates/accounts/profil_form.html
{% extends 'homepage.html' %}

{% block content %}
  <h3>Profil Form</h3>
  <p>Momentan doar pentru Specializarea Matematica, Limba Romana, Anul 1 si 2 sunt adaugate date in baza de date</p>
  <form method="POST" id="profilForm" data-lb-url="{% url 'accounts:ajax_load_lb' %}" data-an-url="{% url 'accounts:ajax_load_an' %}" data-grupa-url="{% url 'accounts:ajax_load_grupa' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
  </form>
  {% if user %}
    <div class="border-top pt-3">

      <a class="btn btn-danger" href="{% url 'accounts:delete_profil'%}">Sterge cont</a>
    </div>

  {% endif %}
{% endblock %}

  {% block script_form %}
  <script>
    $("#id_specializare").change(function () {
      var url = $("#profilForm").attr("data-lb-url");
      var specializareId = $(this).val();
      $.ajax({
        url: url,
        data: {
          'specializare': specializareId
        },
        success: function (data) {
          $("#id_limba_predare").html(data);
        }
      });

    });

    $("#id_limba_predare").change(function () {
      var url = $("#profilForm").attr("data-an-url");
      var limbaPredareId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'limba_predare': limbaPredareId
        },
        success: function (data) {
          $("#id_an").html(data);
        }
      });

    });

    $("#id_an").change(function () {
      var url = $("#profilForm").attr("data-grupa-url");
      var anId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'an': anId
        },
        success: function (data) {
          $("#id_grupa").html(data);
        }
      });

    });


  </script>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "homepage.html" %}
{% block brand %}

<h6>Agenda Student</h6>
{% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token%}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Creeaza cont</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Ai deja un cont?<a class="ml-2" href="{% url 'accounts:login_view' %}">Login</a></small>
        </div>
    </div>

{% endblock %}